[build]
  publish = "www"

# Proxy WebSockets to the cloud game server backend
[[redirects]]
  from = "/ws/*"
  to = "wss://allati-arena.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://allati-arena.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
